name: book_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  service_provider:
    path: ../service_provider

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
